language: go
go:
- "1.11.x"
- "1.12.x"

go_import_path: github.com/pfnet-research/git-ghost

before_install:
- export PATH=$GOPATH/bin:$PATH

install:
- go get -u github.com/golang/dep/...
- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
- go get -u github.com/mattn/goveralls
- dep ensure

before_script: make lint

script:
- make test coverage
- make install e2e

after_success:
- goveralls -coverprofile=profile.cov -service=travis-ci
